/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { PresetTheme, PresetTemplate, CanvasRatio } from './types';

export const BANGLA_FONTS = [
  { id: 'Noto Sans Bengali', name: 'Noto Sans Bengali (মডার্ন ও পরিষ্কার)', css: "'Noto Sans Bengali', sans-serif" },
  { id: 'Hind Siliguri', name: 'Hind Siliguri (জনপ্রিয় ও স্পষ্ট)', css: "'Hind Siliguri', sans-serif" },
  { id: 'Noto Serif Bengali', name: 'Noto Serif Bengali (পত্রিকার মতো)', css: "'Noto Serif Bengali', serif" },
  { id: 'Mina', name: 'Mina (স্টাইলিশ ও গোলগাল)', css: "'Mina', sans-serif" },
  { id: 'Galada', name: 'Galada (ক্যালিগ্রাফি আর্ট)', css: "'Galada', cursive" },
];

export const PRESET_THEMES: PresetTheme[] = [
  {
    id: 'breaking-red',
    name: 'ব্রেকিং রেড (Breaking Red)',
    primary: '#E11D48', // deep crimson red
    secondary: '#FFFFFF',
    darkAccent: '#0F172A', // dark grey / navy
    lightAccent: '#F8FAFC',
    textColor: '#1E293B',
    canvasBg: '#FFFFFF',
  },
  {
    id: 'editorial-dark',
    name: 'ডার্ক এলিট (Premium Dark)',
    primary: '#F59E0B', // gold accent
    secondary: '#1E293B', // dark state color
    darkAccent: '#020617', // dark slate
    lightAccent: '#1E293B',
    textColor: '#F8FAFC',
    canvasBg: '#090D1A',
  },
  {
    id: 'sports-green',
    name: 'স্পোর্টস গ্রিন (Sports Green)',
    primary: '#059669', // cricket green
    secondary: '#FFFFFF',
    darkAccent: '#064E3B', 
    lightAccent: '#F0FDF4',
    textColor: '#022C22',
    canvasBg: '#FFFFFF',
  },
  {
    id: 'lifestyle-pink',
    name: 'সেন্টেল ব্লু (Central Blue)',
    primary: '#2563EB', // vibrant blue
    secondary: '#FFFFFF',
    darkAccent: '#1E3A8A',
    lightAccent: '#EFF6FF',
    textColor: '#1E293B',
    canvasBg: '#FFFFFF',
  },
];

export const PRESET_BACKGROUND_IMAGES = [
  { id: 'news-studio', name: 'নিউজ স্টুডিও ব্লার', url: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1000&auto=format&fit=crop&q=80' },
  { id: 'dhaka-skyline', name: 'ঢাকা সিটি', url: 'https://images.unsplash.com/photo-1629814407887-bdeef2fd2d65?w=1000&auto=format&fit=crop&q=80' },
  { id: 'cricket', name: 'ক্রিকেট স্টেডিয়াম', url: 'https://images.unsplash.com/photo-1540747737956-3787233e5683?w=1000&auto=format&fit=crop&q=80' },
  { id: 'abstract-red', name: 'লাল অ্যাবস্ট্রাক্ট', url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1000&auto=format&fit=crop&q=80' },
  { id: 'slate', name: 'ডার্ক মেটাল টেক্সচার', url: 'https://images.unsplash.com/photo-1533035353720-f1c6a75cd8ab?w=1000&auto=format&fit=crop&q=80' },
];

export const PRESET_MOCK_IMAGES = [
  { id: 'dhaka-rain', name: 'বৃষ্টির ঢাকা ক্রসিং', url: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&auto=format&fit=crop&q=80' },
  { id: 'shakib-al-hasan', name: 'ক্রিকেটার উদযাপন', url: 'https://images.unsplash.com/photo-1531415080290-bc98545ab3ef?w=800&auto=format&fit=crop&q=80' },
  { id: 'national-parliament', name: 'জাতীয় সংসদ ভবন', url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&auto=format&fit=crop&q=80' },
  { id: 'graduates', name: 'শিক্ষার্থীদের সাফল্য', url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80' },
  { id: 'tech-office', name: 'টেক স্টার্টআপ অফিস', url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80' },
];

export const BENGALI_MONTHS = [
  'জানুয়ারি', 'ফেব্রুয়ারি', 'মার্চ', 'এপ্রিল', 'মে', 'জুন',
  'জুলাই', 'আগস্ট', 'সেপ্টেম্বর', 'অক্টোবর', 'নভেম্বর', 'ডিসেম্বর'
];

export const getBanglaDateString = () => {
  const date = new Date(2026, 5, 5); // Target local date from environment: 2026-06-05
  const day = date.getDate().toString().replace(/\d/g, (d) => '০১২৩৪৫৬৭৮৯'[+d]);
  const month = BENGALI_MONTHS[date.getMonth()];
  const year = date.getFullYear().toString().replace(/\d/g, (d) => '০১২৩৪৫৬৭৮৯'[+d]);
  return `ঢাকা, ${day} ${month} ${year}`;
};

export const INITIAL_TEMPLATES: PresetTemplate[] = [
  {
    id: 'breaking-news',
    name: 'Breaking News Standard',
    bengaliName: 'ব্রেকিং নিউজ স্টাইল',
    description: 'সর্বশেষ চাঞ্চল্যকর সংবাদের জন্য আকর্ষণীয় লাল-কালোর ডিজাইন।',
    ratio: '1:1',
    themeId: 'breaking-red',
    canvasBg: '#FFFFFF',
    canvasBgType: 'solid',
    canvasTexture: 'none',
    elements: [
      // Top Red Stripe accent
      {
        id: 'accent-top-bar',
        type: 'shape',
        name: 'টপ হাইলাইট বার',
        x: 0,
        y: 0,
        width: 800,
        height: 15,
        content: 'rectangle',
        style: {
          backgroundColor: '#E11D48',
          opacity: 100,
        },
        shapeType: 'rectangle',
        locked: true,
      },
      // Header Section (Channel Logo and Name)
      {
        id: 'channel-header',
        type: 'logo-header',
        name: 'চ্যানেল লোগো ও নাম',
        x: 40,
        y: 35,
        width: 450,
        height: 50,
        content: 'যমুনা নিউজ ২৪',
        style: {
          color: '#E11D48',
          fontSize: 24,
          fontWeight: '800',
          fontFamily: 'Noto Sans Bengali',
          backgroundColor: 'transparent',
        },
        locked: false,
      },
      // Category Badge
      {
        id: 'category-badge',
        type: 'badge',
        name: 'ক্যাটাগরি ব্যাজ',
        x: 580,
        y: 38,
        width: 140,
        height: 38,
        content: 'ব্রেকিং নিউজ',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#E11D48',
          fontSize: 15,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 6,
          borderWidth: 0,
          paddingY: 6,
        },
        locked: false,
      },
      // Divider Line
      {
        id: 'header-divider',
        type: 'shape',
        name: 'হেডার ডিভাইডার লাইন',
        x: 40,
        y: 95,
        width: 720,
        height: 2,
        content: '',
        style: {
          backgroundColor: '#E2E8F0',
        },
        shapeType: 'line',
        locked: true,
      },
      // Date and Location Badge
      {
        id: 'date-badge',
        type: 'text',
        name: 'তারিখ ও স্থান',
        x: 40,
        y: 110,
        width: 300,
        height: 30,
        content: getBanglaDateString(),
        style: {
          color: '#64748B',
          fontSize: 14,
          fontWeight: '500',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      // News Main Image Block
      {
        id: 'news-image',
        type: 'image',
        name: 'সংবাদ চিত্র',
        x: 40,
        y: 150,
        width: 720,
        height: 380,
        content: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 8,
          borderWidth: 3,
          borderColor: '#E11D48',
          boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
        },
        imageScale: 1.1,
        imageOffsetX: 0,
        imageOffsetY: -10,
        locked: false,
      },
      // Floating Flash Badge inside image
      {
        id: 'live-badge',
        type: 'badge',
        name: 'তাজা খবর ফ্ল্যাশ',
        x: 60,
        y: 170,
        width: 80,
        height: 28,
        content: '● লাইভ',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#E11D48',
          fontSize: 12,
          fontWeight: '800',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          paddingY: 4,
        },
        locked: false,
      },
      // Backdrop Accent Ribbon for Headline (gives that stunning news-channel glow)
      {
        id: 'headline-backing-bar',
        type: 'shape',
        name: 'শিরোনাম ফুটিয়ে তোলার ফিতা',
        x: 40,
        y: 550,
        width: 720,
        height: 8,
        content: '',
        style: {
          backgroundColor: '#E11D48',
          opacity: 90,
        },
        shapeType: 'rectangle',
        locked: false,
      },
      // News Main Headline
      {
        id: 'main-headline',
        type: 'text',
        name: 'প্রধান সংবাদ শিরোনাম',
        x: 40,
        y: 570,
        width: 720,
        height: 85,
        content: 'রাজধানীতে আকস্মিক তীব্র কালবৈশাখী ঝড়, ধানমন্ডিতে বড় গাছ উপড়ে যোগাযোগ বন্ধ!',
        style: {
          color: '#0F172A',
          fontSize: 27,
          lineHeight: 1.35,
          fontWeight: '800',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      // News Subtitle / Brief
      {
        id: 'sub-headline',
        type: 'text',
        name: 'সংক্ষিপ্ত উপ-শিরোনাম',
        x: 40,
        y: 670,
        width: 720,
        height: 65,
        content: 'আজ দুপুরে হঠাৎ শুরু হওয়া ঝড়ে শহরের বিভিন্ন সড়ক স্থবির হয়ে পড়ে। সিটি কর্পোরেশনের কর্মীরা গাছ সরাতে দ্রুত উদ্ধার তৎপরতা শুরু করেছে।',
        style: {
          color: '#475569',
          fontSize: 16,
          lineHeight: 1.5,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      // Footer Accent Ribbon
      {
        id: 'footer-ribbon',
        type: 'shape',
        name: 'ফুটার ফিতা',
        x: 0,
        y: 750,
        width: 800,
        height: 50,
        content: 'rectangle',
        style: {
          backgroundColor: '#0F172A',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      // Brand URL in Footer
      {
        id: 'brand-url',
        type: 'footer',
        name: 'ব্র্যান্ড ওয়েবসাইট',
        x: 40,
        y: 762,
        width: 320,
        height: 26,
        content: 'www.jamunanews24.com',
        style: {
          color: '#F8FAFC',
          fontSize: 14,
          fontWeight: '500',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      // Bullet info or slogan in footer
      {
        id: 'brand-slogan',
        type: 'footer',
        name: 'স্লোগান',
        x: 400,
        y: 762,
        width: 360,
        height: 26,
        content: 'সত্যের সন্ধানে প্রতিনিয়ত | যমুনা ডিজিটাল',
        style: {
          color: '#F59E0B',
          fontSize: 13,
          fontWeight: '600',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'premium-dark-quote',
    name: 'Premium Dark Quote',
    bengaliName: 'এলিট ডার্ক ব্যক্তিত্ব উক্তি',
    description: 'কোনো সফল ব্যক্তিত্বের প্রেরণামূলক সাক্ষাৎকার বা ডার্ক প্রফেশনাল নিউজের জন্য।',
    ratio: '1:1',
    themeId: 'editorial-dark',
    canvasBg: '#0F172A',
    canvasBgType: 'solid',
    canvasTexture: 'none',
    elements: [
      // Top Gold Strip accent
      {
        id: 'gold-top-bar',
        type: 'shape',
        name: 'টপ গোল্ড বার',
        x: 0,
        y: 0,
        width: 800,
        height: 12,
        content: 'rectangle',
        style: {
          backgroundColor: '#F59E0B',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      // Huge Background Quote symbols
      {
        id: 'quote-decorator-left',
        type: 'text',
        name: 'উদ্ধৃতি চিহ্ন ব্যাকগ্রাউন্ড',
        x: 50,
        y: 110,
        width: 150,
        height: 120,
        content: '“',
        style: {
          color: '#1E293B',
          fontSize: 160,
          fontWeight: '800',
          fontFamily: 'Galada',
          opacity: 35,
        },
        locked: true,
      },
      // Editorial Category Badge
      {
        id: 'dark-cat-badge',
        type: 'badge',
        name: 'ক্যাটাগরি ব্যাজ',
        x: 50,
        y: 50,
        width: 110,
        height: 32,
        content: 'বিশেষ সাক্ষাৎকার',
        style: {
          color: '#020617',
          backgroundColor: '#F59E0B',
          fontSize: 13,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          paddingY: 5,
        },
        locked: false,
      },
      // Editorial Logo text
      {
        id: 'editorial-logo',
        type: 'logo-header',
        name: 'মিডিয়া লোগো',
        x: 530,
        y: 48,
        width: 220,
        height: 40,
        content: 'দ্য বেঙ্গল ট্রিবীউন',
        style: {
          color: '#FFFFFF',
          fontSize: 22,
          fontWeight: '700',
          fontFamily: 'Galada',
          textAlign: 'right',
        },
        locked: false,
      },
      // Split layout Left: Big Interview Quote Text in Noto Serif
      {
        id: 'quote-headline',
        type: 'text',
        name: 'প্রধান উদ্ধৃতি সংবাদ',
        x: 50,
        y: 150,
        width: 440,
        height: 340,
        content: '"তরুণ সাংবাদিকদের আধুনিক প্রযুক্তি ও এআই ব্যবহারের বিষয়ে দক্ষতা অর্জন করা এখন সময়ের দাবি। তথ্য যাচাইয়ে প্রযুক্তির প্রয়োজনীয়তা অপরিসীম।"',
        style: {
          color: '#FFFFFF',
          fontSize: 26,
          lineHeight: 1.45,
          fontWeight: '600',
          fontFamily: 'Noto Serif Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      // Detail subtext of interview context
      {
        id: 'quote-context',
        type: 'text',
        name: 'উদ্ধৃতি প্রসঙ্গ ও প্রেক্ষাপট',
        x: 50,
        y: 510,
        width: 440,
        height: 110,
        content: 'ঢাকা বিশ্ববিদ্যালয়ের সাংবাদিকতা বিভাগের বিশেষ সেমিনারে তিনি এই গুরুত্বারোপ করেন। বর্তমান বৈশ্বিক ডিজিটাল বিপ্লবে দেশীয় নিউজ চ্যানেলসমূহের উন্নয়ন এখন অপরিহার্য।',
        style: {
          color: '#94A3B8',
          fontSize: 15,
          lineHeight: 1.5,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      // Split layout Right: Portrait Image Box
      {
        id: 'quotee-image',
        type: 'image',
        name: 'বক্তা ব্যক্তির ছবি',
        x: 510,
        y: 130,
        width: 240,
        height: 320,
        content: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 12,
          borderWidth: 2,
          borderColor: '#F59E0B',
          boxShadow: '0 20px 25px -5px rgba(0,0,0,0.3)',
        },
        imageScale: 1.25,
        imageOffsetX: -10,
        imageOffsetY: -5,
        locked: false,
      },
      // Quote Speaker Name Badge
      {
        id: 'speaker-name',
        type: 'text',
        name: 'বক্তা ব্যক্তির নাম',
        x: 510,
        y: 465,
        width: 240,
        height: 32,
        content: 'ড. আশরাফুল ইসলাম',
        style: {
          color: '#F59E0B',
          fontSize: 18,
          fontWeight: '700',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'center',
        },
        locked: false,
      },
      // Speaker Designation
      {
        id: 'speaker-title',
        type: 'text',
        name: 'বক্তার পদবি',
        x: 510,
        y: 495,
        width: 240,
        height: 30,
        content: 'সাবেক তথ্য উপদেষ্টা ও মিডিয়া গবেষক',
        style: {
          color: '#94A3B8',
          fontSize: 12,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
        },
        locked: false,
      },
      // Subtle elegant accent line
      {
        id: 'quote-bottom-divider',
        type: 'shape',
        name: 'ফুটার ডিভাইডার লাইন',
        x: 50,
        y: 690,
        width: 700,
        height: 1,
        content: '',
        style: {
          backgroundColor: '#334155',
        },
        shapeType: 'line',
        locked: true,
      },
      // Footer web and socials
      {
        id: 'dark-footer-url',
        type: 'footer',
        name: 'ফুটার লিংক',
        x: 50,
        y: 715,
        width: 350,
        height: 30,
        content: 'www.thebengaltribune.press',
        style: {
          color: '#64748B',
          fontSize: 14,
          fontWeight: '500',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'dark-footer-date',
        type: 'footer',
        name: 'তারিখ প্রদর্শন',
        x: 430,
        y: 715,
        width: 320,
        height: 30,
        content: getBanglaDateString(),
        style: {
          color: '#64748B',
          fontSize: 14,
          fontWeight: '500',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'sports-victory',
    name: 'Sports Victory Theme',
    bengaliName: 'খেলাধুলা ও গৌরব গাথা',
    description: 'ক্রিকেট বা ফুটবল খেলার আপডেট বা দেশের বড় কোনো বিজয়ের ঘোষণার জন্য নিখুঁত স্পোর্টিং ডিজাইন।',
    ratio: '1:1',
    themeId: 'sports-green',
    canvasBg: '#FFFFFF',
    canvasBgType: 'gradient',
    canvasGradient: 'linear-gradient(135deg, #F0FDF4 0%, #FFFFFF 100%)',
    canvasTexture: 'none',
    elements: [
      // Top Green Stripe accent
      {
        id: 'sports-top-bar',
        type: 'shape',
        name: 'টপ গ্রিন ফিতা',
        x: 0,
        y: 0,
        width: 800,
        height: 14,
        content: 'rectangle',
        style: {
          backgroundColor: '#059669',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      // Category Sports Badge
      {
        id: 'sports-cat-badge',
        type: 'badge',
        name: 'ক্যাটাগরি ব্যাজ',
        x: 40,
        y: 35,
        width: 120,
        height: 38,
        content: 'ক্রীড়াঙ্গন',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#059669',
          fontSize: 15,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 20, // Rounded-full oval style
          paddingY: 6,
        },
        locked: false,
      },
      // Sports Channel Title
      {
        id: 'sports-logo',
        type: 'logo-header',
        name: 'স্পোর্টস লোগো টেক্সট',
        x: 520,
        y: 33,
        width: 240,
        height: 40,
        content: 'খেলাযোগ ২৪',
        style: {
          color: '#064E3B',
          fontSize: 27,
          fontWeight: '800',
          fontFamily: 'Mina',
          textAlign: 'right',
        },
        locked: false,
      },
      // News Main Image Block: Sports Star illustration
      {
        id: 'sports-image',
        type: 'image',
        name: 'খেলোয়াড়ের বিজয়ী ছবি',
        x: 40,
        y: 95,
        width: 720,
        height: 410,
        content: 'https://images.unsplash.com/photo-1531415080290-bc98545ab3ef?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 16,
          borderWidth: 4,
          borderColor: '#059669',
          boxShadow: '0 10px 25px -5px rgba(5, 150, 105, 0.15)',
        },
        imageScale: 1.05,
        imageOffsetX: 0,
        imageOffsetY: 0,
        locked: false,
      },
      // Match result overlay
      {
        id: 'score-overlay-badge',
        type: 'badge',
        name: 'ফলাফল ওভারলে ব্যাজ',
        x: 60,
        y: 115,
        width: 170,
        height: 40,
        content: 'ঐতিহাসিক সিরিজ জয়',
        style: {
          color: '#022C22',
          backgroundColor: '#F7FEE7',
          fontSize: 14,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 8,
          borderWidth: 1,
          borderColor: '#A3E635',
          paddingY: 7,
        },
        locked: false,
      },
      // Sports Headline
      {
        id: 'sports-headline',
        type: 'text',
        name: 'সংবাদ শিরোনাম',
        x: 40,
        y: 530,
        width: 720,
        height: 90,
        content: 'টাইগারদের অবিস্মরণীয় পারফরম্যান্স: লর্ডসের মাঠে ঐতিহাসিক ব্যবধানে সিরিজ জয়!',
        style: {
          color: '#064E3B',
          fontSize: 26,
          lineHeight: 1.35,
          fontWeight: '800',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'center',
        },
        locked: false,
      },
      // Short editorial / congrats text
      {
        id: 'sports-subtext',
        type: 'text',
        name: 'উপ-শিরোনাম সংবাদ',
        x: 40,
        y: 635,
        width: 720,
        height: 60,
        content: 'শেষ ওভারে অসাধারণ বোলিংয়ে চার উইকেট নিয়ে জয় নিশ্চিত করলেন তাসকিন। এই নিয়ে ওয়ানডে ক্রিকেটে বিদেশের মাটিতে বাংলাদেশের শততম অসাধারণ গৌরব এটি।',
        style: {
          color: '#374151',
          fontSize: 15,
          lineHeight: 1.45,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
        },
        locked: false,
      },
      // Gold Ribbons decoration below headline
      {
        id: 'sports-accent-strip',
        type: 'shape',
        name: 'ডিজাইন বার গ্রিন',
        x: 250,
        y: 710,
        width: 300,
        height: 3,
        content: '',
        style: {
          backgroundColor: '#A3E635',
        },
        shapeType: 'line',
        locked: true,
      },
      // Footer URL / Date
      {
        id: 'sports-footer-url',
        type: 'footer',
        name: 'ফুটার লিংক',
        x: 40,
        y: 745,
        width: 320,
        height: 25,
        content: 'sports.khelajog24.com',
        style: {
          color: '#064E3B',
          fontSize: 13,
          fontWeight: '600',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'sports-footer-date',
        type: 'footer',
        name: 'তারিখ তথ্য',
        x: 440,
        y: 745,
        width: 320,
        height: 25,
        content: getBanglaDateString(),
        style: {
          color: '#059669',
          fontSize: 13,
          fontWeight: '600',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'political-national',
    name: 'National Governance',
    bengaliName: 'জাতীয় উন্নয়ন ও সংবাদ',
    description: 'জাতীয় বা রাজনৈতিক গুরুত্বপূর্ণ সিদ্ধান্ত, বাজেট বা সংসদীয় সংবাদের জন্য উপযুক্ত প্রফেশনাল ও গম্ভীর লুক।',
    ratio: '4:5', // 4:5 Portrait templates! Very trendy for Facebook / Instagram posts
    themeId: 'breaking-red',
    canvasBg: '#FAFAFA',
    canvasBgType: 'solid',
    canvasTexture: 'none',
    elements: [
      // Top elegant accent line
      {
        id: 'nat-stripe-top',
        type: 'shape',
        name: 'টপ ডাবল স্ট্রাইপ',
        x: 0,
        y: 0,
        width: 800,
        height: 18,
        content: 'rectangle',
        style: {
          backgroundColor: '#0F172A',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      // National Red Dot indicator
      {
        id: 'nat-red-accent',
        type: 'shape',
        name: 'রেড অ্যাকসেন্ট বার',
        x: 0,
        y: 18,
        width: 800,
        height: 5,
        content: 'rectangle',
        style: {
          backgroundColor: '#DC2626',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      // Editorial Logo text
      {
        id: 'nat-logo',
        type: 'logo-header',
        name: 'পত্রিকা লোগো',
        x: 50,
        y: 45,
        width: 350,
        height: 55,
        content: 'দৈনিক জাতীয় বার্তা',
        style: {
          color: '#0F172A',
          fontSize: 28,
          fontWeight: '800',
          fontFamily: 'Noto Serif Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      // Category tag (Red Ribbon)
      {
        id: 'nat-cat-badge',
        type: 'badge',
        name: 'ক্যাটাগরি ব্যাজ',
        x: 620,
        y: 45,
        width: 130,
        height: 38,
        content: 'জাতীয় সংবাদ',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#0F172A',
          fontSize: 14,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 0, // Flat square block look
          paddingY: 7,
        },
        locked: false,
      },
      // Header Divider Line
      {
        id: 'nat-divider',
        type: 'shape',
        name: 'বিভাজক রেখা',
        x: 50,
        y: 110,
        width: 700,
        height: 2,
        content: '',
        style: {
          backgroundColor: '#0F172A',
        },
        shapeType: 'line',
        locked: true,
      },
      // Location / Editor tagline
      {
        id: 'nat-sublabel',
        type: 'text',
        name: 'মফস্বল ও ডেটলাইন',
        x: 50,
        y: 125,
        width: 400,
        height: 30,
        content: getBanglaDateString() + ' | বিশেষ ক্রোডপত্র',
        style: {
          color: '#DC2626',
          fontSize: 14,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      // Portrait Ratio Main Image 4:5 optimized
      {
        id: 'nat-image',
        type: 'image',
        name: 'জাতীয় সংসদের ছবি',
        x: 50,
        y: 165,
        width: 700,
        height: 440, // Elegant large portrait frame
        content: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 8,
          borderWidth: 2,
          borderColor: '#E2E8F0',
          boxShadow: '0 4px 12px rgba(0,0,0,0.05)',
        },
        imageScale: 1.1,
        imageOffsetX: 0,
        imageOffsetY: -30,
        locked: false,
      },
      // Headline (Noto Serif Bengali - Newspaper Elegant format)
      {
        id: 'nat-headline',
        type: 'text',
        name: 'প্রধান খবর শিরোনাম',
        x: 50,
        y: 635,
        width: 700,
        height: 120, // 4:5 has extra vertical space!
        content: 'উন্নয়নের মহাপরিকল্পনা: স্মার্ট সিটি বিনির্মাণে জাতীয় সংসদে নতুন বাজেট ঘোষণা!',
        style: {
          color: '#0F172A',
          fontSize: 32,
          lineHeight: 1.45,
          fontWeight: '700',
          fontFamily: 'Noto Serif Bengali',
          textAlign: 'left',
          textDecoration: 'none',
        },
        locked: false,
      },
      // Paragraph content
      {
        id: 'nat-paragraph',
        type: 'text',
        name: 'বিস্তারিত সাব-প্যারাগ্রাফ',
        x: 50,
        y: 770,
        width: 700,
        height: 100,
        content: 'আজ অর্থমন্ত্রী সংসদ অধিবেশনে এই বিশাল অংকের রূপরেখা তুলে ধরেন। শিক্ষা, যোগাযোগ ব্যবস্থা ও প্রযুক্তির আধুনিকায়নে সর্বোচ্চ বরাদ্দ প্রস্তাব করা হয়েছে, যা তরুণ সমাজকে স্বাবলম্বী করার নতুন সুযোগ সৃষ্টি করবে।',
        style: {
          color: '#334155',
          fontSize: 16,
          lineHeight: 1.6,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      // Elegant underline line
      {
        id: 'bottom-accent',
        type: 'shape',
        name: 'অ্যাকসেন্ট লাইন রেড',
        x: 50,
        y: 915,
        width: 150,
        height: 4,
        content: '',
        style: {
          backgroundColor: '#DC2626',
        },
        shapeType: 'rectangle',
        locked: false,
      },
      // Footer web address
      {
        id: 'nat-footer',
        type: 'footer',
        name: 'ফুটার লিংক',
        x: 50,
        y: 940,
        width: 400,
        height: 30,
        content: 'e-paper.jatiyabarta.com.bd',
        style: {
          color: '#475569',
          fontSize: 14,
          fontWeight: '600',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      // Security badge or disclaimer
      {
        id: 'nat-footer-right',
        type: 'footer',
        name: 'মিডিয়া কোড',
        x: 500,
        y: 940,
        width: 250,
        height: 30,
        content: 'নিউজ কোড: #৯০৮৭০২',
        style: {
          color: '#94A3B8',
          fontSize: 12,
          fontWeight: '500',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'weather-alert',
    name: 'Weather Alert Block',
    bengaliName: 'আবহাওয়া সতর্কবার্তা ও পূর্বাভাস',
    description: 'টানা বজ্রবৃষ্টি, সাইক্লোন বা আবহাওয়ার বিশেষ সতর্কবার্তার জন্য নীল ও গোল্ডেন ডিজাইনের সুন্দর ক্যানভাস।',
    ratio: '1:1',
    themeId: 'lifestyle-pink',
    canvasBg: '#0F172A',
    canvasBgType: 'gradient',
    canvasGradient: 'linear-gradient(135deg, #1E1B4B 0%, #0F172A 100%)',
    canvasTexture: 'none',
    elements: [
      {
        id: 'weather-accent-top',
        type: 'shape',
        name: 'টপ আবহাওয়া ফিতা',
        x: 0,
        y: 0,
        width: 800,
        height: 12,
        content: 'rectangle',
        style: {
          backgroundColor: '#3B82F6',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'weather-header',
        type: 'logo-header',
        name: 'আবহাওয়া লোগো',
        x: 40,
        y: 35,
        width: 450,
        height: 50,
        content: 'আবহাওয়া ২৪.কম (Weather24)',
        style: {
          color: '#3B82F6',
          fontSize: 24,
          fontWeight: '800',
          fontFamily: 'Mina',
        },
        locked: false,
      },
      {
        id: 'weather-cat-badge',
        type: 'badge',
        name: 'সতর্কতা ক্যাটাগরি',
        x: 550,
        y: 38,
        width: 210,
        height: 38,
        content: 'মহাবিপদ সংকেত ৮',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#EF4444',
          fontSize: 14,
          fontWeight: '800',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 6,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'weather-divider-line',
        type: 'shape',
        name: 'বিভাজক রেখা',
        x: 40,
        y: 95,
        width: 720,
        height: 2,
        content: '',
        style: {
          backgroundColor: '#1E293B',
        },
        shapeType: 'line',
        locked: true,
      },
      {
        id: 'weather-date',
        type: 'text',
        name: 'তারিখ',
        x: 40,
        y: 110,
        width: 300,
        height: 30,
        content: getBanglaDateString(),
        style: {
          color: '#94A3B8',
          fontSize: 14,
          fontWeight: '500',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'weather-image',
        type: 'image',
        name: 'ঝড় বা দেশের বৃষ্টি চিত্র',
        x: 40,
        y: 150,
        width: 720,
        height: 380,
        content: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 8,
          borderWidth: 2,
          borderColor: '#EF4444',
          boxShadow: '0 10px 15px -3px rgba(0,0,0,0.3)',
        },
        imageScale: 1.15,
        imageOffsetX: 0,
        imageOffsetY: -20,
        locked: false,
      },
      {
        id: 'temp-overlay-badge',
        type: 'badge',
        name: 'তাপমাত্রা ও আবহাওয়া পূর্বাভাস',
        x: 60,
        y: 168,
        width: 260,
        height: 38,
        content: '🌧️ তাপমাত্রা: ২৩°সে. | অতি ভারী বর্ষণ',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#1E3A8A',
          fontSize: 13,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'weather-backing-bar',
        type: 'shape',
        name: 'অ্যাকসেন্ট নিওন ফিতা',
        x: 40,
        y: 550,
        width: 720,
        height: 8,
        content: '',
        style: {
          backgroundColor: '#F59E0B',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'weather-headline',
        type: 'text',
        name: 'আবহাওয়া শিরোনাম',
        x: 40,
        y: 570,
        width: 720,
        height: 95,
        content: 'বঙ্গোপসাগরে তীব্র গভীর নিম্নচাপ ঘনীভূত: উপকূলের ১০ জেলায় আকস্মিক জলোচ্ছ্বাসের আশঙ্কা!',
        style: {
          color: '#FFFFFF',
          fontSize: 27,
          lineHeight: 1.35,
          fontWeight: '800',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'weather-subtitle',
        type: 'text',
        name: 'আবহাওয়া বিবরণ বিবরণী',
        x: 40,
        y: 675,
        width: 720,
        height: 65,
        content: 'সব ধরণের মাছ ধরার ট্রলারকে দ্রুত নিরাপদ ঘাটে ফিরে আসার অতি জরুরি নির্দেশ দেয়া হয়েছে। মোংলা ও পায়রা সমুদ্রবন্দরকে ৮ নম্বর মহাবিপদ সংকেত দেখিয়ে যেতে বলা হয়েছে।',
        style: {
          color: '#94A3B8',
          fontSize: 15,
          lineHeight: 1.45,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'weather-footer-bg',
        type: 'shape',
        name: 'ফুটার পটভূমি',
        x: 0,
        y: 755,
        width: 800,
        height: 45,
        content: 'rectangle',
        style: {
          backgroundColor: '#1E1B4B',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'weather-footer-url',
        type: 'footer',
        name: 'আবহাওয়া সংস্থা লিংক',
        x: 40,
        y: 766,
        width: 350,
        height: 25,
        content: 'www.bangladesh-weather-portal.gov.bd',
        style: {
          color: '#A5F3FC',
          fontSize: 13,
          fontWeight: '500',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'weather-footer-right',
        type: 'footer',
        name: 'সবার আগে সতর্কবার্তা',
        x: 440,
        y: 766,
        width: 320,
        height: 25,
        content: 'আবহাওয়া সতর্কতা | জাতীয় ক্রাইসিস ইউনিট',
        style: {
          color: '#FFFFFF',
          fontSize: 12,
          fontWeight: '600',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'business-gold',
    name: 'Business Economy News',
    bengaliName: 'ব্যবসায়িক সূচক ও বাজার দর',
    description: 'শেয়ার বাজার, স্বর্ণের মূল্যের রেকর্ড উত্থান-পতন বা বাণিজ্যিক ও অর্থনৈতিক বিশেষ সংবাদের জন্য লাক্সারি ডার্ক লুক লেআউট।',
    ratio: '1:1',
    themeId: 'editorial-dark',
    canvasBg: '#111827',
    canvasBgType: 'solid',
    canvasTexture: 'none',
    elements: [
      {
        id: 'biz-accent-top',
        type: 'shape',
        name: 'টপ গোল্ড অ্যাকসেন্ট',
        x: 0,
        y: 0,
        width: 800,
        height: 12,
        content: 'rectangle',
        style: {
          backgroundColor: '#F59E0B',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'biz-header',
        type: 'logo-header',
        name: 'বাণিজ্যিক লোগো টেক্সট',
        x: 40,
        y: 35,
        width: 450,
        height: 50,
        content: 'দৈনিক বাণিজ্যিক দর্পন',
        style: {
          color: '#F59E0B',
          fontSize: 24,
          fontWeight: '800',
          fontFamily: 'Noto Serif Bengali',
        },
        locked: false,
      },
      {
        id: 'biz-cat-badge',
        type: 'badge',
        name: 'অর্থ ও বাণিজ্য ক্যাটাগরি',
        x: 580,
        y: 38,
        width: 180,
        height: 38,
        content: 'বৈশ্বিক অর্থনীতি',
        style: {
          color: '#000000',
          backgroundColor: '#F59E0B',
          fontSize: 14,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'biz-divider-line',
        type: 'shape',
        name: 'বিভাজক রেখা',
        x: 40,
        y: 95,
        width: 720,
        height: 2,
        content: '',
        style: {
          backgroundColor: '#374151',
        },
        shapeType: 'line',
        locked: true,
      },
      {
        id: 'biz-date',
        type: 'text',
        name: 'তারিখ',
        x: 40,
        y: 110,
        width: 300,
        height: 30,
        content: getBanglaDateString(),
        style: {
          color: '#9CA3AF',
          fontSize: 14,
          fontWeight: '500',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'biz-image',
        type: 'image',
        name: 'বিনিয়োগ ও স্বর্ণের চিত্র',
        x: 40,
        y: 150,
        width: 720,
        height: 380,
        content: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 8,
          borderWidth: 2,
          borderColor: '#F59E0B',
          boxShadow: '0 10px 15px -3px rgba(0,0,0,0.5)',
        },
        imageScale: 1.1,
        imageOffsetX: 0,
        imageOffsetY: -10,
        locked: false,
      },
      {
        id: 'biz-status-badge',
        type: 'badge',
        name: 'রেকর্ড মূল্য হাইলাইট',
        x: 60,
        y: 168,
        width: 280,
        height: 38,
        content: '📈 প্রতি ভরি সোনার রেকর্ড দাম ১,২৫,০০০৳',
        style: {
          color: '#000000',
          backgroundColor: '#FFFBEB',
          fontSize: 13,
          fontWeight: '800',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'biz-backing-bar',
        type: 'shape',
        name: 'স্বর্ণালী ফুটার লাইন',
        x: 40,
        y: 550,
        width: 720,
        height: 6,
        content: '',
        style: {
          backgroundColor: '#F59E0B',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'biz-headline',
        type: 'text',
        name: 'বাণিজ্যিক শিরোনাম',
        x: 40,
        y: 570,
        width: 720,
        height: 95,
        content: 'অস্থিতিশীল বৈশ্বিক বাজার: বাংলাদেশে ইতিহাসে প্রথমবারের মতো সোনার ভরি ১ লাখ ২৫ হাজার টাকা ছাড়াল!',
        style: {
          color: '#FFFFFF',
          fontSize: 27,
          lineHeight: 1.35,
          fontWeight: '850',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'biz-subtitle',
        type: 'text',
        name: 'বাণিজ্যিক সংক্ষিপ্ত কথা',
        x: 40,
        y: 675,
        width: 720,
        height: 65,
        content: 'আন্তর্জাতিক বাজারে লাগাতার মূল্যবৃদ্ধি এবং স্থানীয় লিকুইড কারেন্সি সংকটের কারণে জুয়েলার্স অ্যাসোসিয়েশন নতুন এই দাম কার্যকরের ঘোষণা করেছে। স্থবির হয়ে পড়েছে দেশীয় গহনার বাজার।',
        style: {
          color: '#9CA3AF',
          fontSize: 15,
          lineHeight: 1.45,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'biz-footer',
        type: 'footer',
        name: 'বাণিজ্য লিংক',
        x: 40,
        y: 755,
        width: 320,
        height: 25,
        content: 'business.dorpon-news.com',
        style: {
          color: '#F59E0B',
          fontSize: 13,
          fontWeight: '600',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'biz-footer-right',
        type: 'footer',
        name: 'অর্থনীতি ইনডেক্স',
        x: 440,
        y: 755,
        width: 320,
        height: 25,
        content: 'সূচক আপডেট: +৩.৫২% | বাণিজ্য বিভাগ',
        style: {
          color: '#6B7280',
          fontSize: 12,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'celebrity-quote',
    name: 'Celebrity Quote Block',
    bengaliName: 'ব্যক্তিত্ব ও ভাইরাল সোশ্যাল কোট',
    description: 'খেলোয়াড়, তারকা, সফল ব্যক্তিত্বদের ভাইরাল মন্তব্য বা সোশ্যাল মিডিয়ার বিখ্যাত উক্তি উদ্ধৃতি করতে চমৎকার ৪:৫ পোস্টার ডিজাইন।',
    ratio: '4:5',
    themeId: 'breaking-red',
    canvasBg: '#FCFCF9',
    canvasBgType: 'solid',
    canvasTexture: 'none',
    elements: [
      {
        id: 'quote-stripe-top',
        type: 'shape',
        name: 'টপ রিবন অ্যাকসেন্ট',
        x: 0,
        y: 0,
        width: 800,
        height: 15,
        content: 'rectangle',
        style: {
          backgroundColor: '#E11D48',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'quote-header',
        type: 'logo-header',
        name: 'সোশ্যাল লোগো',
        x: 50,
        y: 40,
        width: 400,
        height: 50,
        content: 'সোশ্যাল কর্নার বার্তা (Social Highlight)',
        style: {
          color: '#1E293B',
          fontSize: 22,
          fontWeight: '800',
          fontFamily: 'Mina',
        },
        locked: false,
      },
      {
        id: 'quote-cat-badge',
        type: 'badge',
        name: 'উক্তি ব্যাজ',
        x: 600,
        y: 40,
        width: 150,
        height: 36,
        content: 'ভাইরাল পোস্ট',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#0F172A',
          fontSize: 13,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'quote-divider',
        type: 'shape',
        name: 'বিভাজক রেখা',
        x: 50,
        y: 95,
        width: 700,
        height: 2,
        content: '',
        style: {
          backgroundColor: '#E2E8F0',
        },
        shapeType: 'line',
        locked: true,
      },
      {
        id: 'quote-bengali-decorator-quotes',
        type: 'text',
        name: 'উদ্ধৃতি বিশালাকার চিহ্ন',
        x: 45,
        y: 110,
        width: 180,
        height: 180,
        content: '“',
        style: {
          color: '#E11D48',
          fontSize: 240,
          fontWeight: '900',
          fontFamily: 'Galada',
          opacity: 12,
        },
        locked: true,
      },
      {
        id: 'quote-image-avatar',
        type: 'image',
        name: 'ব্যক্তিত্ব গোল ছবি',
        x: 60,
        y: 140,
        width: 210,
        height: 210,
        content: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 105,
          borderWidth: 4,
          borderColor: '#E11D48',
          boxShadow: '0 10px 15px -3px rgba(225, 29, 72, 0.2)',
        },
        imageScale: 1.35,
        imageOffsetX: 0,
        imageOffsetY: -10,
        locked: false,
      },
      {
        id: 'quotee-name',
        type: 'text',
        name: 'ব্যক্তিত্ব উক্তিদাতার নাম',
        x: 300,
        y: 200,
        width: 450,
        height: 40,
        content: 'তামিম ইকবাল',
        style: {
          color: '#0F172A',
          fontSize: 27,
          fontWeight: '800',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'quotee-title',
        type: 'text',
        name: 'উক্তিদাতার পদবি',
        x: 300,
        y: 245,
        width: 450,
        height: 35,
        content: 'সাবেক ক্রিকেট অধিনায়ক ও তারকা ওপেনার',
        style: {
          color: '#DC2626',
          fontSize: 14,
          fontWeight: '600',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'quotee-source-date',
        type: 'text',
        name: 'মিডিয়া উক্তি উৎস',
        x: 300,
        y: 280,
        width: 450,
        height: 30,
        content: 'ফেসবুক ভেরিফাইড পৃষ্ঠা থেকে সংগৃহীত',
        style: {
          color: '#64748B',
          fontSize: 12,
          fontWeight: '500',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'quote-main-speech',
        type: 'text',
        name: 'প্রধান উদ্ধৃতি বক্তব্য',
        x: 50,
        y: 450,
        width: 700,
        height: 340,
        content: '“ক্রিকেটের সবুজ মাঠে লড়াইয়ের সময় সবসময় হয়তো শতভাগ ট্রফি ঘরে তোলা সম্ভব হয় না, কিন্তু দেশের মাটিতে লাল-সবুজের জার্সি গায়ে নিজের সবটুকু উজাড় করে দেওয়াটাই প্রতিটি দেশপ্রেমিক খেলোয়াড়ের পরম গৌরব। ভক্তদের ভালোবাসাই আমাদের খেলার মূল চালিকাশক্তি।”',
        style: {
          color: '#0F172A',
          fontSize: 23,
          lineHeight: 1.55,
          fontWeight: '600',
          fontFamily: 'Noto Serif Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'quote-sub-highlight',
        type: 'text',
        name: 'বক্তব্য প্রসঙ্গ কথা',
        x: 50,
        y: 780,
        width: 700,
        height: 100,
        content: 'সাম্প্রতিক এক ফেসবুক লাইভ সাক্ষাৎকারে দেশীয় ক্রিকেটের সার্বিক ক্রান্তিকালীন উত্তরণ এবং তরুণ খেলোয়াড়দের প্রতি পূর্ণ সমর্থন ব্যক্ত করে তিনি এই আবেগঘন পরামর্শ দেন, যা ইতিমধ্যেই মুহূর্তেই সামাজিক যোগাযোগ মাধ্যমে তুমুল সাড়া ফেলেছে।',
        style: {
          color: '#475569',
          fontSize: 15,
          lineHeight: 1.5,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'quote-footer-right',
        type: 'footer',
        name: 'তারিখ তথ্য',
        x: 430,
        y: 938,
        width: 320,
        height: 30,
        content: getBanglaDateString(),
        style: {
          color: '#64748B',
          fontSize: 13,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'entertainment-news',
    name: 'Entertainment Cinema Buzz',
    bengaliName: 'বিনোদন, শোবিজ ও সিনেমা গ্ল্যামার',
    description: 'মিডিয়া গসিপ, তারকাদের লাইফস্টাইল, আসন্ন সিনেমা রিলিজ বা বিনোদন জগতের মেগা সংবাদের জন্য আকর্ষণীয় থিম।',
    ratio: '1:1',
    themeId: 'lifestyle-pink',
    canvasBg: '#1E1B4B',
    canvasBgType: 'gradient',
    canvasGradient: 'linear-gradient(135deg, #2E1065 0%, #0F172A 100%)',
    canvasTexture: 'none',
    elements: [
      {
        id: 'ent-top-accent',
        type: 'shape',
        name: 'রঙিন টপ ফিতা',
        x: 0,
        y: 0,
        width: 800,
        height: 12,
        content: 'rectangle',
        style: {
          backgroundColor: '#EC4899',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'ent-logo',
        type: 'logo-header',
        name: 'বিনোদন লোগো',
        x: 40,
        y: 35,
        width: 450,
        height: 50,
        content: 'সিনেপ্লেক্স স্টারস (CineStars)',
        style: {
          color: '#F472B6',
          fontSize: 24,
          fontWeight: '800',
          fontFamily: 'Mina',
        },
        locked: false,
      },
      {
        id: 'ent-cat-badge',
        type: 'badge',
        name: 'শোবিজ ব্যাজ',
        x: 580,
        y: 38,
        width: 180,
        height: 38,
        content: 'হল আপডেট ও শোবিজ',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#EC4899',
          fontSize: 13,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 6,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'ent-divider',
        type: 'shape',
        name: 'হেডার লাইন',
        x: 40,
        y: 95,
        width: 720,
        height: 2,
        content: '',
        style: {
          backgroundColor: '#4C1D95',
        },
        shapeType: 'line',
        locked: true,
      },
      {
        id: 'ent-date',
        type: 'text',
        name: 'তারিখ',
        x: 40,
        y: 110,
        width: 300,
        height: 30,
        content: getBanglaDateString(),
        style: {
          color: '#C084FC',
          fontSize: 14,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'ent-image',
        type: 'image',
        name: 'নাটক/সিনেমার পোস্টার ছবি',
        x: 40,
        y: 150,
        width: 720,
        height: 380,
        content: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 8,
          borderWidth: 2,
          borderColor: '#EC4899',
          boxShadow: '0 10px 25px -5px rgba(236, 72, 153, 0.3)',
        },
        imageScale: 1.1,
        imageOffsetX: 0,
        imageOffsetY: 0,
        locked: false,
      },
      {
        id: 'ent-trending-badge',
        type: 'badge',
        name: 'ট্রেন্ডিং সাইন',
        x: 60,
        y: 168,
        width: 180,
        height: 35,
        content: '🔥 মেগা ট্রেলার রিলিজ',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#9333EA',
          fontSize: 12,
          fontWeight: '800',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          paddingY: 5,
        },
        locked: false,
      },
      {
        id: 'ent-accent-line',
        type: 'shape',
        name: 'ডিজাইন বার',
        x: 40,
        y: 550,
        width: 720,
        height: 6,
        content: '',
        style: {
          backgroundColor: '#D946EF',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'ent-headline',
        type: 'text',
        name: 'বিনোদন শিরোনাম',
        x: 40,
        y: 570,
        width: 720,
        height: 95,
        content: 'অবশেষে প্রতীক্ষার অবসান: বিগ বাজেট অ্যাকশন মুভি নিয়ে রূপালি পর্দায় ফিরছেন মেগাস্টার শাকিব খান!',
        style: {
          color: '#FFFFFF',
          fontSize: 27,
          lineHeight: 1.35,
          fontWeight: '850',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'ent-subtext',
        type: 'text',
        name: 'শোবিজ ডিটেইলস',
        x: 40,
        y: 675,
        width: 720,
        height: 65,
        content: 'সদ্য প্রকাশিত ৩ মিনিটের দুর্দান্ত অ্যাকশন ট্রেলারটি রিলিজের মাত্র ১ ঘণ্টায় রেকর্ড ৩ মিলিয়ন ভিউ অতিক্রম করে সোশ্যাল মিডিয়ায় হৈচৈ সৃষ্টি করেছে। প্রযোজকদের আগামী ঈদে এটি বিশ্বব্যাপী ১০০টিরও বেশি সিনেমা হলে মুক্তির জোর পরিকল্পনা রয়েছে।',
        style: {
          color: '#D8B4FE',
          fontSize: 15,
          lineHeight: 1.45,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'ent-footer',
        type: 'footer',
        name: 'বিনোদন লিংক',
        x: 40,
        y: 755,
        width: 320,
        height: 25,
        content: 'stars.cinemaworld24.com',
        style: {
          color: '#D946EF',
          fontSize: 13,
          fontWeight: '600',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'ent-footer-right',
        type: 'footer',
        name: 'সোর্স তথ্য',
        x: 440,
        y: 755,
        width: 320,
        height: 25,
        content: 'সর্বশেষ শোবিজ গসিপ আপডেট',
        style: {
          color: '#A78BFA',
          fontSize: 13,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'education-jobs',
    name: 'Education Job Circular',
    bengaliName: 'চাকরি, শিক্ষা ও ক্যারিয়ার সার্কুলার',
    description: 'নতুন বিসিএস, প্রাইমারি শিক্ষক নিয়োগ, ব্যাংকিং বা যেকোনো সরকারি/বেসরকারি বড় চাকরির বিজ্ঞপ্তি ও তথ্যপ্রকাশের পরিচ্ছন্ন ডিজাইন।',
    ratio: '1:1',
    themeId: 'lifestyle-pink',
    canvasBg: '#F8FAFC',
    canvasBgType: 'solid',
    canvasTexture: 'none',
    elements: [
      {
        id: 'edu-top-accent',
        type: 'shape',
        name: 'টপ বর্ডার বার',
        x: 0,
        y: 0,
        width: 800,
        height: 12,
        content: 'rectangle',
        style: {
          backgroundColor: '#1E3A8A',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'edu-logo',
        type: 'logo-header',
        name: 'শিক্ষা লোগো টেক্সট',
        x: 40,
        y: 35,
        width: 450,
        height: 50,
        content: 'বিডি ক্যারিয়ার ডটকম (BDCareer)',
        style: {
          color: '#1E3A8A',
          fontSize: 24,
          fontWeight: '800',
          fontFamily: 'Noto Sans Bengali',
        },
        locked: false,
      },
      {
        id: 'edu-cat-badge',
        type: 'badge',
        name: 'শিক্ষা ক্যাটাগরি',
        x: 580,
        y: 38,
        width: 180,
        height: 38,
        content: 'চাকরির বিজ্ঞপ্তি',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#2563EB',
          fontSize: 14,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 6,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'edu-divider',
        type: 'shape',
        name: 'ডিভাইডার লাইন',
        x: 40,
        y: 95,
        width: 720,
        height: 2,
        content: '',
        style: {
          backgroundColor: '#E2E8F0',
        },
        shapeType: 'line',
        locked: true,
      },
      {
        id: 'edu-date',
        type: 'text',
        name: 'তারিখ',
        x: 40,
        y: 110,
        width: 300,
        height: 30,
        content: getBanglaDateString(),
        style: {
          color: '#64748B',
          fontSize: 14,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'edu-image',
        type: 'image',
        name: 'শিক্ষা বা ক্যারিয়ার সাফল্য চিত্র',
        x: 40,
        y: 150,
        width: 720,
        height: 380,
        content: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 8,
          borderWidth: 2,
          borderColor: '#CBD5E1',
          boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
        },
        imageScale: 1.15,
        imageOffsetX: 0,
        imageOffsetY: -10,
        locked: false,
      },
      {
        id: 'edu-meta-badge',
        type: 'badge',
        name: 'আবেদন সময়সীমা',
        x: 60,
        y: 168,
        width: 250,
        height: 36,
        content: '📅 আবেদন শেষ: চলতি মাসের ৩০ তারিখ',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#DC2626',
          fontSize: 12,
          fontWeight: '800',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'edu-stripe-under',
        type: 'shape',
        name: 'ডিজাইন বার ২',
        x: 40,
        y: 550,
        width: 720,
        height: 6,
        content: '',
        style: {
          backgroundColor: '#2563EB',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'edu-headline',
        type: 'text',
        name: 'শিক্ষা শিরোনাম',
        x: 40,
        y: 570,
        width: 720,
        height: 95,
        content: 'প্রাথমিক বিদ্যালয়সমূহে রেকর্ড ১০,০০০ সহকারী শিক্ষক নিয়োগের চূড়ান্ত ফল প্রকাশ: উত্তীর্ণদের তালিকা অনলাইনে!',
        style: {
          color: '#1E293B',
          fontSize: 27,
          lineHeight: 1.35,
          fontWeight: '850',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'edu-subtext',
        type: 'text',
        name: 'শিক্ষা বিবরণী',
        x: 40,
        y: 675,
        width: 720,
        height: 65,
        content: 'প্রাথমিক শিক্ষা অধিদফতর নিজস্ব ভেরিফাইড ওয়েবসাইটে নির্বাচিত প্রার্থীদের রোল নম্বর প্রকাশ করেছে। দ্রুত আপনার ফলাফল ও চূড়ান্ত গেজেট দেখতে নিচে দেওয়া লিংকে ক্লিক করুন বা কিউআর কোড স্ক্যান করুন।',
        style: {
          color: '#475569',
          fontSize: 15,
          lineHeight: 1.45,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'edu-footer',
        type: 'footer',
        name: 'সার্কুলার পোর্টাল লিংক',
        x: 40,
        y: 755,
        width: 320,
        height: 25,
        content: 'www.dpe.gov.bd/result-portal',
        style: {
          color: '#1E3A8A',
          fontSize: 13,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'edu-footer-right',
        type: 'footer',
        name: 'সোর্স হেল্পলাইন',
        x: 440,
        y: 755,
        width: 320,
        height: 25,
        content: 'হেল্পলাইন: ১৬২২২ | প্রাথমিক শিক্ষা বোর্ড',
        style: {
          color: '#64748B',
          fontSize: 13,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'tech-gadget',
    name: 'Technology AI Review',
    bengaliName: 'বিজ্ঞান, তথ্যপ্রযুক্তি ও এআই কোণ',
    description: 'স্মার্টফোন রিভিউ, কৃত্রিম বুদ্ধিমত্তা (এআই), চমৎকার গ্যাজেট রিলিজ বা বিজ্ঞানভিত্তিক পোস্টার তৈরির জন্য মডার্ন টেকনিক্যাল গাঢ় নীল থিম।',
    ratio: '1:1',
    themeId: 'editorial-dark',
    canvasBg: '#0B0F19',
    canvasBgType: 'gradient',
    canvasGradient: 'linear-gradient(135deg, #020617 0%, #0F172A 100%)',
    canvasTexture: 'none',
    elements: [
      {
        id: 'tech-top-stripe',
        type: 'shape',
        name: 'সাইবার নিওন টপ দাগ',
        x: 0,
        y: 0,
        width: 800,
        height: 12,
        content: 'rectangle',
        style: {
          backgroundColor: '#06B6D4',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'tech-logo',
        type: 'logo-header',
        name: 'টেক চ্যানেল লোগো',
        x: 40,
        y: 35,
        width: 450,
        height: 50,
        content: 'ডিজিটাল গ্যাজেট ট্র্যাক (TechTrack)',
        style: {
          color: '#06B6D4',
          fontSize: 24,
          fontWeight: '800',
          fontFamily: 'Mina',
        },
        locked: false,
      },
      {
        id: 'tech-cat-badge',
        type: 'badge',
        name: 'টেক ক্যাটাগরি',
        x: 580,
        y: 38,
        width: 180,
        height: 38,
        content: 'তথ্যপ্রযুক্তি ও এআই',
        style: {
          color: '#000000',
          backgroundColor: '#06B6D4',
          fontSize: 14,
          fontWeight: '800',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 6,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'tech-divider',
        type: 'shape',
        name: 'ডিভাইডার লাইন',
        x: 40,
        y: 95,
        width: 720,
        height: 2,
        content: '',
        style: {
          backgroundColor: '#1E293B',
        },
        shapeType: 'line',
        locked: true,
      },
      {
        id: 'tech-date',
        type: 'text',
        name: 'তারিখ',
        x: 40,
        y: 110,
        width: 300,
        height: 30,
        content: getBanglaDateString(),
        style: {
          color: '#64748B',
          fontSize: 14,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'tech-image',
        type: 'image',
        name: 'স্মার্টফোন/এআই ইমেজ',
        x: 40,
        y: 150,
        width: 720,
        height: 380,
        content: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 8,
          borderWidth: 2,
          borderColor: '#06B6D4',
          boxShadow: '0 10px 25px -5px rgba(6, 182, 212, 0.4)',
        },
        imageScale: 1.15,
        imageOffsetX: 0,
        imageOffsetY: -10,
        locked: false,
      },
      {
        id: 'tech-model-badge',
        type: 'badge',
        name: 'মডেল স্পেসিফিকেশন',
        x: 60,
        y: 168,
        width: 200,
        height: 36,
        content: '🚀 বাংলা সাপোর্টযুক্ত ৩.৫ এআই',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#0F172A',
          fontSize: 11,
          fontWeight: '800',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          borderWidth: 1,
          borderColor: '#06B6D4',
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'tech-stripe-under',
        type: 'shape',
        name: 'ডিজাইন বার ৩',
        x: 40,
        y: 550,
        width: 720,
        height: 6,
        content: '',
        style: {
          backgroundColor: '#0891B2',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'tech-headline',
        type: 'text',
        name: 'বিজ্ঞান শিরোনাম',
        x: 40,
        y: 570,
        width: 720,
        height: 95,
        content: 'বাংলা ভাষা অনুবাদের অপার বিপ্লব: রিলিজ হলো সর্বাধুনিক আর্টিফিশিয়াল ইন্টেলিজেন্স মডেল লার্জ-বাংলা!',
        style: {
          color: '#FFFFFF',
          fontSize: 27,
          lineHeight: 1.35,
          fontWeight: '850',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'tech-subtext',
        type: 'text',
        name: 'টেক বিবরণী',
        x: 40,
        y: 675,
        width: 720,
        height: 65,
        content: 'নতুন এই মডেলটি সম্পূর্ণ নির্ভুলভাবে আঞ্চলিক কথ্য বাংলা বুঝতে সক্ষম। এটি দীর্ঘ সাহিত্য রচনা থেকে শুরু করে জটিল প্রাতিষ্ঠানিক কোডিং ও আইনি নথিপত্রের বাংলা অনুবাদ করবে নিখুঁত দক্ষতার সাথে।',
        style: {
          color: '#94A3B8',
          fontSize: 15,
          lineHeight: 1.45,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'tech-footer',
        type: 'footer',
        name: 'টেক ওয়েবসাইট',
        x: 40,
        y: 755,
        width: 320,
        height: 25,
        content: 'ai-portal.techtrack24.org',
        style: {
          color: '#06B6D4',
          fontSize: 13,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'tech-footer-right',
        type: 'footer',
        name: 'টেক ডাটা আপডেট',
        x: 440,
        y: 755,
        width: 320,
        height: 25,
        content: 'আর্টিফিশিয়াল ইন্টেলিজেন্স রিসার্চ ইউনিট',
        style: {
          color: '#475569',
          fontSize: 13,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
  {
    id: 'health-lifestyle',
    name: 'Health Care Alert',
    bengaliName: 'স্বাস্থ্যসেবা, সচেতনতা ও লাইফস্টাইল',
    description: 'ডেঙ্গু সিজন গাইডলাইন, করোনা বা অন্যান্য মহামারী সচেতনতা এবং প্রতিদিনের জরুরি সুস্বাস্থ্য টিপসের আকর্ষণীয় গ্রিন লেআউট।',
    ratio: '1:1',
    themeId: 'sports-green',
    canvasBg: '#FFFFFF',
    canvasBgType: 'solid',
    canvasTexture: 'none',
    elements: [
      {
        id: 'hlth-top-stripe',
        type: 'shape',
        name: 'স্বাস্থ্য সবুজ টপ দাগ',
        x: 0,
        y: 0,
        width: 800,
        height: 12,
        content: 'rectangle',
        style: {
          backgroundColor: '#059669',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'hlth-logo',
        type: 'logo-header',
        name: 'স্বাস্থ্য লোগো',
        x: 40,
        y: 35,
        width: 450,
        height: 50,
        content: 'সুস্বাস্থ্য বার্তা ২৪ (HealthCare)',
        style: {
          color: '#059669',
          fontSize: 24,
          fontWeight: '800',
          fontFamily: 'Noto Sans Bengali',
        },
        locked: false,
      },
      {
        id: 'hlth-cat-badge',
        type: 'badge',
        name: 'ক্যাটাগরি ব্যাজ',
        x: 580,
        y: 38,
        width: 180,
        height: 38,
        content: 'জনস্বাস্থ্য সচেতনতা',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#059669',
          fontSize: 14,
          fontWeight: '800',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 6,
          paddingY: 6,
        },
        locked: false,
      },
      {
        id: 'hlth-divider',
        type: 'shape',
        name: 'বিভাজক রেখা',
        x: 40,
        y: 95,
        width: 720,
        height: 2,
        content: '',
        style: {
          backgroundColor: '#E2E8F0',
        },
        shapeType: 'line',
        locked: true,
      },
      {
        id: 'hlth-date',
        type: 'text',
        name: 'তারিখ',
        x: 40,
        y: 110,
        width: 300,
        height: 30,
        content: getBanglaDateString(),
        style: {
          color: '#64748B',
          fontSize: 14,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'hlth-image',
        type: 'image',
        name: 'সুস্বাস্থ্য ও লাইফস্টাইল ছবি',
        x: 40,
        y: 150,
        width: 720,
        height: 380,
        content: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&auto=format&fit=crop&q=80',
        style: {
          borderRadius: 8,
          borderWidth: 2,
          borderColor: '#A7F3D0',
          boxShadow: '0 10px 15px -3px rgba(5, 150, 105, 0.15)',
        },
        imageScale: 1.15,
        imageOffsetX: 0,
        imageOffsetY: -10,
        locked: false,
      },
      {
        id: 'hlth-alert-badge',
        type: 'badge',
        name: 'অ্যালার্ট সাইন',
        x: 60,
        y: 168,
        width: 230,
        height: 35,
        content: '🦟 বর্ষার ডেঙ্গু প্রতিরোধ গাইড',
        style: {
          color: '#FFFFFF',
          backgroundColor: '#EF4444',
          fontSize: 12,
          fontWeight: '800',
          fontFamily: 'Hind Siliguri',
          textAlign: 'center',
          borderRadius: 4,
          paddingY: 5,
        },
        locked: false,
      },
      {
        id: 'hlth-stripe-under',
        type: 'shape',
        name: 'ডিজাইন বার ৪',
        x: 40,
        y: 550,
        width: 720,
        height: 6,
        content: '',
        style: {
          backgroundColor: '#10B981',
        },
        shapeType: 'rectangle',
        locked: true,
      },
      {
        id: 'hlth-headline',
        type: 'text',
        name: 'স্বাস্থ্য শিরোনাম',
        x: 40,
        y: 570,
        width: 720,
        height: 95,
        content: 'বর্ষার প্রকোপে সারা দেশে লাফিয়ে বাড়ছে ডেঙ্গু জ্বর: চিকিৎসকদের জেনেশুনে সতর্ক থাকার ৫ জরুরি পরামর্শ!',
        style: {
          color: '#1E293B',
          fontSize: 27,
          lineHeight: 1.35,
          fontWeight: '850',
          fontFamily: 'Noto Sans Bengali',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'hlth-subtext',
        type: 'text',
        name: 'স্বাস্থ্য বিবরণী',
        x: 40,
        y: 675,
        width: 720,
        height: 65,
        content: 'বাড়ির চারপাশ পরিষ্কার রাখুন, ফুলের টব ও ডাবের খোসায় জমে থাকা পানি ৩ দিনের মধ্যে অপসারণ করুন। ঘুমানোর সময় অবশ্যই মশারি ব্যবহার করুন এবং তীব্র জ্বর এলে চিকিৎসকের পরামর্শে প্লাটিলেট পরীক্ষা করান।',
        style: {
          color: '#475569',
          fontSize: 15,
          lineHeight: 1.45,
          fontWeight: '400',
          fontFamily: 'Hind Siliguri',
          textAlign: 'left',
        },
        locked: false,
      },
      {
        id: 'hlth-footer',
        type: 'footer',
        name: 'স্বাস্থ্য অধিদপ্তর লিংক',
        x: 40,
        y: 755,
        width: 320,
        height: 25,
        content: 'www.dghs.gov.bd/dengue-awareness',
        style: {
          color: '#059669',
          fontSize: 13,
          fontWeight: '700',
          fontFamily: 'Hind Siliguri',
        },
        locked: false,
      },
      {
        id: 'hlth-footer-right',
        type: 'footer',
        name: 'তথ্যসূত্র',
        x: 440,
        y: 755,
        width: 320,
        height: 25,
        content: 'স্বাস্থ্য ও সচেতনতা ইউনিট | বাংলাদেশ স্বাস্থ্যসেবা',
        style: {
          color: '#64748B',
          fontSize: 13,
          fontWeight: '550',
          fontFamily: 'Hind Siliguri',
          textAlign: 'right',
        },
        locked: false,
      },
    ],
  },
];


